name: libraw_dart
description: LibRaw Dart bindings
version: 1.0.0
repository: https://github.com/igorskh/libraw_dart

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  ffigen: ^19.0.0
